# What is numpy?

We can store data in multi dimensional array's

# Numpy Vs. List

List's are very slow while numpy are very fast
* The reason is that numpy uses fixed type (where only the number it self is stored without any other information but in lists it stores many other factors inturn increasing the size of the no. of bits to store each number).
* The data in an numpy array are all the same type but for lists it is different it can have many types
* Contiguous Memory, the data is scatterd every where in the memory when it comes to list but numpy has data sequentially inorder and right next to each other, we wont need to store the order and other usless info that is stored when using lists

# Applications of NumPy?
- MATLAB Replacement
- ML

# The Basics

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
a = np.array([1,2,3])

In [3]:
# append, delete
a = np.append(a,5)
print(a)
a = np.delete(a,2) 
print(a)

[1 2 3 5]
[1 2 5]


In [4]:
a.shape

(3,)

In [5]:
a.dtype

dtype('int64')

In [6]:
a.ndim,a.shape

(1, (3,))

In [7]:
b = np.array([
    [9.0,8.0,7.0],
    [6.0,5.0,4.0]
])

In [8]:
b.shape,b.ndim

((2, 3), 2)

In [9]:
b.astype(int)

array([[9, 8, 7],
       [6, 5, 4]])

In [10]:
a.itemsize # no. of bites per element

8

In [11]:
a.size # total no. of elements

3

In [12]:
a.nbytes # tot. no of bytes

24

# Accessing /Changin specific elements, rows, columns, etc...

In [13]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [14]:
a[1,5] # a[0][5]

13

In [15]:
a.shape

(2, 7)

In [16]:
# [r, c]
a[1,5]

13

In [17]:
# Get specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
a[:,5]

array([ 6, 13])

In [19]:
# [startidx:endidx:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [20]:
a[1,5] = 20

In [21]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [22]:
a[:,2] = [5,2]

In [23]:
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

# Initalizing Different types of arrays

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [26]:
np.full(5,2) # shape, the no.

array([2, 2, 2, 2, 2])

In [27]:
np.full_like(a,4) # np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [28]:
# Random decimal numbers
np.random.rand(5)

array([0.68989984, 0.83679452, 0.88983497, 0.4986312 , 0.74293551])

In [29]:
np.random.randn(5)

array([-0.7664737 , -0.22288964, -1.46721527,  0.39834152,  0.87599694])

In [30]:
np.random.randint(6)

5

In [31]:
# Random intelgar values
np.random.randint(1,5,size=(5,2))

array([[2, 1],
       [2, 3],
       [3, 1],
       [3, 4],
       [2, 4]])

In [32]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
arr=np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

# Copying arrays

In [34]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [35]:
b = a.copy() # !important

In [36]:
b[2] = 100

In [37]:
a,b

(array([1, 2, 3]), array([  1,   2, 100]))

# Mathematics

In [38]:
a = np.array([1,2,3,4])

In [39]:
a

array([1, 2, 3, 4])

In [40]:
a + 2

array([3, 4, 5, 6])

In [41]:
a - 2

array([-1,  0,  1,  2])

In [42]:
a*2

array([2, 4, 6, 8])

In [43]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [44]:
a ** 2

array([ 1,  4,  9, 16])

In [45]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [46]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [47]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

## Linear Algebra

In [48]:
a = np.ones(
    (2,3)
)
b = np.full((3,2),2)
a,b

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[2, 2],
        [2, 2],
        [2, 2]]))

In [49]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [50]:
# Find the determinant
c = np.identity(2)
np.linalg.det(c)

1.0

In [51]:
c

array([[1., 0.],
       [0., 1.]])

## Statistics

In [52]:
stats = np.array([
    [1,2,3],
    [4,5,6]
])

In [53]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
np.min(stats)

1

In [55]:
np.max(stats)

6

In [56]:
np.sum(stats)

21

## Reorganizing Arrays

In [57]:
before = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

In [58]:
before.shape

(2, 4)

In [59]:
after=before.reshape(8,1)

In [60]:
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

## Load/Save  data


In [61]:
# np.genfromtext('data.txt',delimiter=',')

In [62]:
np.save('text.np',after)

In [63]:
after_loaded = np.load('./text.np.npy')

In [64]:
after_loaded==after

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])